# Generated by Django 3.1 on 2020-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('year', models.SmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('odometer', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
