# Generated by Django 3.1 on 2020-11-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
