# Generated by Django 3.1 on 2020-11-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scar', '0002_auto_20201112_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
