# Generated by Django 3.1 on 2020-11-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scar', '0005_remove_use_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
